source 'https://rubygems.org'

ruby '2.0.0'
gem 'rails', '3.2.16'

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
end


group :production do
  gem 'pg'
end

group :assets do
  gem 'uglifier'
end

gem 'jquery-rails'
gem 'haml'


